version: "3.8"

services:
    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P123456p
            MYSQL_DATABASE: phonebook_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: ummu_1
        volumes:
            - db-data:/var/lib/mysql
        configs:
            - source: table
              target: /docker-entrypoint-initdb.d/init.sql
        networks:
            - ummunet
    app-server:
        image: "597161409065.dkr.ecr.us-east-1.amazonaws.com/ummu-repo/phonebook-app:latest"
        deploy:
            mode: global
            update_config:
                parallelism: 2
                delay: 5s
                order: start-first
        ports:
            - "80:80"
        networks:
            - ummunet
networks:
    ummunet: 
        driver: overlay

volumes:
    db-data:
 
configs:
    table:
        file: ./init.sql